### ISSUE TITLE
Support for Ref::map

### ISSUE THREAD

**Issue by jgarvin** [Xeiron/ref_thread_local.rs#4]
Useful method on `RefCell`, seems like it would still be useful for ref_thread_locals.

**Comment by tuxzz** [comment]
Hi jgarvin,

Good idea. I'm now planning to implement `Ref::map`, `Ref::map_split` and other useful functions from `RefCell`.
It's also welcome to send a PR if you think it's urgent.

**Comment by tuxzz** [comment]
Released with version `0.1.0`

**Comment by jgarvin** [comment]
Awesome, thanks!
